// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvFqihTj7XEBuZLhynSJ03pV42IAugO5c',
    appId: '1:633495833462:web:0a8aa0ee1f4229e5364857',
    messagingSenderId: '633495833462',
    projectId: 'fir-flutter-codelab-71872',
    authDomain: 'fir-flutter-codelab-71872.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-71872.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtur_RapUNuRsV3jcPKgeza2wKRthPUC4',
    appId: '1:633495833462:android:17f76e18953b2bd5364857',
    messagingSenderId: '633495833462',
    projectId: 'fir-flutter-codelab-71872',
    storageBucket: 'fir-flutter-codelab-71872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpLIWNr1wqwvIFvYgD5yehZPzeaK_owo',
    appId: '1:633495833462:ios:ff9df27bb0e461fe364857',
    messagingSenderId: '633495833462',
    projectId: 'fir-flutter-codelab-71872',
    storageBucket: 'fir-flutter-codelab-71872.appspot.com',
    iosBundleId: 'com.example.hadiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpLIWNr1wqwvIFvYgD5yehZPzeaK_owo',
    appId: '1:633495833462:ios:2e0685df56cb3b91364857',
    messagingSenderId: '633495833462',
    projectId: 'fir-flutter-codelab-71872',
    storageBucket: 'fir-flutter-codelab-71872.appspot.com',
    iosBundleId: 'com.example.hadiya.RunnerTests',
  );
}
